title: Vishal Kumar Choudhary
logo: /assets/img/Vishal_Photo.jpg
description:
<p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/public-profile/settings?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_contact-info%3B3Ro4LiPARzS%2BOoIhyYwhXQ%3D%3D">LinkedIn</a> |
  <a href="https://github.com/VISHALKr-CHOUDHARY">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>
theme: jekyll-theme-minimal
